[build-system]
requires=["setuptools", "wheel"]

[tool.pytest.ini_options]
markers=[
    "data_eval: Evaluate dataframe tests",
    "file_eval: Evaluate dataframe from file tests",
]
python_classes="*Tests"
python_files=["*Tests.py"]
testpaths=["tests"]
